export const Cart = {
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    ADD_TO_WISHLIST: 'ADD TO WISHLIST',
    INCREASE_QUANTITY: 'INCREASE_QUANTITY',
    DECREASE_QUANTITY: 'DECREASE_QUANTITY',
    TOTAL_PRICE_CHECK: 'TOTAL_PRICE_CHECK'
}

export const Wislist = {
    ADD_TO_WISH: 'ADD_TO_WISH',
    REMOVE_FROM_WISH: 'REMOVE_FROM_WISH',
    MOVE_TO_CART: 'MOVE_TO_CART'
}

export const Filter = {
    CATEGORY: 'CATEGORY',
    RATINGS: 'RATINGS',
    HIGH_TO_LOW: 'HIGH_TO_LOW',
    LOW_TO_HIGH: 'LOW_TO_HIGH',
    MAX_PRICE: 'MAX_PRICE',
    MIN_PRICE: 'MIN_PRICE'
}